// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igwqgkltzhotvgzshgwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlnd3Fna2x0emhvdHZnenNoZ3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzU3NjUsImV4cCI6MjA3MDI1MTc2NX0.UXy7BC-kKkv-PxyScf_hbamDZy76M5yI9IxiNSN16-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});